import { jsPDF } from "jspdf";

export interface NoticeViolation {
  clause: string;
  title: string;
  severity?: string | null;
  extracted?: string | null;
  remediation?: string | null;
}

export interface NoticeData {
  productName: string;
  brand: string;
  category: string;
  status: string;
  officer: string;
  violations: NoticeViolation[];
}

const money = (s: string | null | undefined) => (s ?? "").replace(/₹/g, "Rs. ");

export function buildNoticePdf(d: NoticeData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = 0;

  // Header band
  doc.setFillColor(16, 22, 30);
  doc.rect(0, 0, W, 96, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text("METROLOGYCHECK AI", M, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(160, 180, 170);
  doc.text("Legal Metrology Division — Packaged Commodities (LMPC) Rules, 2011", M, 56);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("OFFICIAL VIOLATION NOTICE", M, 78);
  y = 128;

  // Meta block
  doc.setTextColor(30, 34, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const meta: [string, string][] = [
    ["Product", d.productName],
    ["Brand", d.brand || "—"],
    ["Category", d.category || "General"],
    ["Inspecting Officer", d.officer],
    ["Audit Result", d.status],
    ["Date of Inspection", new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })],
  ];
  for (const [k, v] of meta) {
    doc.setFont("helvetica", "bold");
    doc.text(`${k}:`, M, y);
    doc.setFont("helvetica", "normal");
    doc.text(doc.splitTextToSize(money(v), W - M * 2 - 130), M + 130, y);
    y += 18;
  }

  y += 14;

  // Violations
  if (d.violations.length === 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(d.status === "COMPLIANT" ? "No statutory violations detected." : "Findings pending manual review.", M, y);
    y += 24;
  } else {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`Statutory Violations (${d.violations.length})`, M, y);
    y += 18;

    d.violations.forEach((v, i) => {
      if (y > 720) {
        doc.addPage();
        y = 64;
      }
      doc.setDrawColor(210, 214, 220);
      doc.line(M, y - 8, W - M, y - 8);
      doc.setFont("courier", "bold");
      doc.setFontSize(10);
      doc.text(`${i + 1}. [${v.clause}]`, M, y + 6);
      doc.setFont("helvetica", "bold");
      doc.text(doc.splitTextToSize(money(v.title), W - M * 2 - 130), M + 130, y + 6);
      y += 22;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(80, 86, 94);
      if (v.extracted) {
        const lines = doc.splitTextToSize(`Extracted: ${money(v.extracted)}`, W - M * 2 - 16);
        doc.text(lines, M + 16, y);
        y += lines.length * 12 + 4;
      }
      if (v.remediation) {
        const lines = doc.splitTextToSize(`Remediation: ${money(v.remediation)}`, W - M * 2 - 16);
        doc.text(lines, M + 16, y);
        y += lines.length * 12 + 4;
      }
      doc.setTextColor(30, 34, 40);
      y += 14;
    });
  }

  // Footer on every page
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setDrawColor(210, 214, 220);
    doc.line(M, 792, W - M, 792);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(110, 116, 124);
    doc.text("Generated by MetrologyCheck AI · For enforcement use only · Not a legal service", M, 806);
    doc.text(`Page ${p} of ${pages}`, W - M - 60, 806);
  }

  doc.save(`violation-notice-${d.productName.toLowerCase().replace(/\s+/g, "-")}.pdf`);
}
